### ISSUE TITLE
Weird style on uploader

### ISSUE THREAD

**Issue by mlaco** [neagle/gokibitz#49] opened 2015-03-10 10:09 UTC
![image](https://cloud.githubusercontent.com/assets/4466642/6572858/0366dda6-c6ec-11e4-80e5-e5d103f9274f.png)

**Comment by neagle** [comment] 2015-03-10 14:33
Yikes! That is _ugly_. It looks like it was caused by my "fix" for long links in comments: 0abf71e75228d4405a92b3d20d438f76b2bc76f5

This is fixed by e20c854e3ad0539a0511302c1331dd30537c32bc.

Thanks a lot: you've done me a big favor by pointing this out.

**Closed by neagle** 2015-03-10 14:33 UTC

**Comment by mlaco** [comment] 2015-03-10 14:40
No problem ^^
