### ISSUE TITLE
Feature Request - Don't make new moves adjust the history in the back button. 

### ISSUE THREAD

**Issue by Yxven** [neagle/gokibitz#105] opened 2015-07-08 01:58 UTC
I clicked to review some guy's game from reddit. I browsed the game (which worked well). I hit back to return to reddit, but it goes back a move. I go back 50 moves to the end of my history, and reddit is gone. This is not expected browser behavior. Having to reopen reddit, navigate to the right sub, and find that guys post so I can give feedback is a pain.

**Comment by sphaso** [comment] 2015-07-09 10:06
I think the issue here is that each move in a game actually has its own URL (as you can notice in the address bar, GoKibitz adds a ?path=xx), so in a sense it is the expected browser behavior.           
I'm curious to read @neagle take on this.

**Comment by neagle** [comment] 2015-07-09 14:15
@Yxven: Sorry about the difficulty you had!

Having each move be treated as an individual page in terms of your browser history is by design, for the reasons that @sphaso mentions. Each move has its own comment thread and path so that individual moves can be linked to, shared, and discussed.

That said, I can sympathize with your experience, too, and am genuinely ambivalent about what the right solution here is. It would be technically possible to still have each move have its own path without adding an item to the browser history, but it'll take some more thought / convincing to be persuaded that it's the right thing to do.

So, for the moment, I'm closing this and sticking with the original behavior, but that doesn't mean I'm unwilling to listen to further argument. Thanks for taking the time to submit an issue!

**Closed by neagle** 2015-07-09 14:15 UTC

**Comment by Yxven** [comment] 2015-07-09 17:33
It's actually similar to youtube. Being able to link to specific parts of video is useful, but since wrecking your history every time you watch a 50+ second video is undesired, it doesn't change the url every second. It provides a "share" option that lets you specify where you want linked.

https://youtu.be/avaSdC0QOUM?t=41s

**Comment by neagle** [comment] 2015-07-09 17:43
Hm: I don't really see navigating through a game as comparable to watching a video, it's more like reading through a message thread on a forum, to my mind.

**Comment by Yxven** [comment] 2015-07-09 18:45
Ok, link me to one forum that changes your url 50 times as you read a thread. They too let you link to an individual post with a "share" or "perma link" button.

**Comment by neagle** [comment] 2015-07-09 19:04
You're right that the pagination on a forum thread - to which I was referring - is likely to be smaller in number than the moves on a go game.

**Comment by neagle** [comment] 2015-07-09 19:06
Keep in mind that shareability isn't the only reason I prefer the current design: I also prefer the current behavior of the back button, which lets you walk back through a game and its conversations.

**Comment by Yxven** [comment] 2015-07-09 19:13
You don't have to choose between those features. We can have a working history and convenient sgf navigation. Use the left and right arrow keys to navigate the sgf. That also doesn't break if you want to navigate a game that's longer than 50 moves.

**Comment by neagle** [comment] 2015-07-09 19:32
I'll give it some thought! Thanks for taking the time to make your argument. :) I'll touch base with my project collaborator @levelonedev in a day or two and talk it over.

**Comment by neagle** [comment] 2015-07-10 17:48
Just a note: in browsing through a game right now, I was interrupted by a notification of new replies on several comments I'd made earlier. I clicked on the notification, was taken to the move in question, then hit back on my browser to go back to the point in the game I'd been at before. It served as a reminder that browsing through games is not necessarily linear, and using recent browser history can be quite useful when you're not just burning linearly through an entire game.

**Comment by levelonedev** [comment] 2015-07-12 18:48
It also helps on mobile when I fat finger the end of game button instead of the next move button. How it is now, the back button will just bring me to where I was. In your case I can't immediately revisit the move I was on.
